# Generated by Django 3.0.5 on 2020-04-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
