# Generated by Django 3.0.5 on 2020-05-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
