# Generated by Django 3.0.5 on 2020-05-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0021_auto_20200520_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
