# Generated by Django 3.0.5 on 2020-05-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0024_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
