# Generated by Django 3.0.5 on 2020-05-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0026_auto_20200521_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainPage.Player'),
        ),
    ]
