# Generated by Django 3.0.5 on 2020-05-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0027_comment_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
