# Generated by Django 3.0.5 on 2020-05-22 11:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0028_auto_20200522_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
