# Generated by Django 3.0.5 on 2020-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0030_auto_20200602_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
