# Generated by Django 3.0.5 on 2020-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0035_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.FileField(default='card1.jpg', null=True, upload_to=''),
        ),
    ]
