# Generated by Django 3.0.5 on 2020-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0036_auto_20200604_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='card1.jpg', null=True, upload_to=''),
        ),
    ]
